

<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">

//This page is a result of an autogenerated content made by running test.html with firefox.

function domo(){

 

   // Binding keys

   $('*').bind('keydown', 'Ctrl+a', function assets() {

       window.location.href = BASE_URL + '/administrator/Test/add';

       return false;

   });



   $('*').bind('keydown', 'Ctrl+f', function assets() {

       $('#sbtn').trigger('click');

       return false;

   });



   $('*').bind('keydown', 'Ctrl+x', function assets() {

       $('#reset').trigger('click');

       return false;

   });



   $('*').bind('keydown', 'Ctrl+b', function assets() {



       $('#reset').trigger('click');

       return false;

   });

}



jQuery(document).ready(domo);

</script>

<!-- Content Header (Page header) -->

<section class="content-header">

   <h1>

      Test<small> <i class="fa fa-chevron-right"></i> <i class="label bg-yellow"><?= $test_counts; ?>  <?= cclang('items'); ?></i></small>

   </h1>

   <ol class="breadcrumb">

      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>

      <li class="active">Test</li>

   </ol>

</section>

<!-- Main content -->

<section class="content">

   <div class="row" >

      

      <div class="col-md-12">

         <div class="box box-warning">

            <div class="box-body ">

               <!-- Widget: user widget style 1 -->

               <div class="box box-widget widget-user-2">

              


                  <form name="form_test" id="form_test" action="<?= base_url('administrator/test/index'); ?>">
 

               <div class="row">
                     <div class="col-md-4"></div>
                     <div class="col-md-8">
                        <div class="col-sm-4 " > 
                        </div>
                       
                        <div class="col-sm-5  " >
                        <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                        </div>
                        <input type="hidden" name="f" id="field" value="">
                       
                        <div class="col-sm-1 ">
                            <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                                 Filter
                              </button>
                        </div>
                        <div class="col-sm-1 ">
                           <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/test');?>" title="<?= cclang('reset_filter'); ?>">
                             <i class="fa fa-undo"></i>
                           </a>
                        </div>
                        <div class="col-sm-1 "> 
                             <?php is_allowed('test_add', function(){?>
                             <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="<?= cclang('add_new_button', ['Test']); ?>  (Ctrl+a)" href="<?=  site_url('administrator/test/add'); ?>"><i class="fa fa-plus-square-o" ></i></a>
                           <?php }) ?>
                                                   </div>
                     </div>
                  </div>





                  <div class="table-responsive"> 

                  <table class="table table-condensed dataTable dataTable">

                     <thead>

                        <tr class="">

                           <!-- <th>

                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">

                           </th> -->

                           <th>Designation</th>

                           <th>Date</th>

                           <th>Action</th>

                        </tr>

                     </thead>

       <tbody id="tbody_test">
                     <?php foreach($tests as $test): ?>
                        <tr>
                           <!-- <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $test->id; ?>">
                           </td> -->
                           
                           <td><?= _ent($test->designation_commune); ?></td> 
                           <td><?= _ent($test->date_test); ?></td> 
                           <td width="200">
                              <?php is_allowed('test_view', function() use ($test){?>
                              <a style="margin-right: 2px" href="<?= site_url('administrator/test/view/' . $test->id); ?>"  class="btn btn-warning btn-xs"><i class="fa fa-eye-slash"></i></a>
                              <?php }) ?>
                              <?php is_allowed('test_update', function() use ($test){?>
                              <a href="<?= site_url('administrator/test/edit/' . $test->id); ?>" class="btn btn-info btn-xs"><i class="fa fa-pencil " ></i> </a>
                              <?php }) ?>
                              <?php is_allowed('test_delete', function() use ($test){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/test/delete/' . $test->id); ?>" class="btn btn-danger btn-xs  remove-data"><i class="fa fa-close"></i></a>
                               <?php }) ?>
                           </td>
                        </tr>
                      <?php endforeach; ?>
                      <?php if ($test_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Test data is not available
                           </td>
                         </tr>
                      <?php endif; ?>
                     </tbody>

                  </table>

                  </div>

               </div>

                               </form>                               <div class="col-md-4 pull-right">
                                    <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                                       <?= $pagination; ?>
                                    </div>
                               </div>


            </div>

            <!--/box body -->

         </div>

         <!--/box -->

      </div>

   </div>

</section>

<!-- /.content -->



<!-- Page script -->

<script>

  $(document).ready(function(){

    $('.remove-data').click(function(){
      var url = $(this).attr('data-href');

      swal({

          title: "<?= cclang('are_you_sure'); ?>",

          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",

          type: "warning",

          showCancelButton: true,

          confirmButtonColor: "#DD6B55",

          confirmButtonText: "<?= cclang('yes_delete_it'); ?>",

          cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",

          closeOnConfirm: true,

          closeOnCancel: true

        },

        function(isConfirm){

          if (isConfirm) {

            document.location.href = url;            

          }

        });



      return false;

    });





    $('#apply').click(function(){



      var bulk = $('#bulk');

      var serialize_bulk = $('#form_test').serialize();



      if (bulk.val() == 'delete') {

         swal({

            title: "<?= cclang('are_you_sure'); ?>",

            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",

            type: "warning",

            showCancelButton: true,

            confirmButtonColor: "#DD6B55",

            confirmButtonText: "<?= cclang('yes_delete_it'); ?>",

            cancelButtonText: "<?= cclang('no_cancel_plx'); ?>",

            closeOnConfirm: true,

            closeOnCancel: true

          },

          function(isConfirm){

            if (isConfirm) {

               document.location.href = BASE_URL + '/administrator/test/delete?' + serialize_bulk;      

            }

          });



        return false;



      } else if(bulk.val() == '')  {

          swal({

            title: "Upss",

            text: "<?= cclang('please_choose_bulk_action_first'); ?>",

            type: "warning",

            showCancelButton: false,

            confirmButtonColor: "#DD6B55",

            confirmButtonText: "Okay!",

            closeOnConfirm: true,

            closeOnCancel: true

          });



        return false;

      }



      return false;



    });/*end appliy click*/





    //check all

    var checkAll = $('#check_all');

    var checkboxes = $('input.check');



    checkAll.on('ifChecked ifUnchecked', function(event) {   

        if (event.type == 'ifChecked') {

            checkboxes.iCheck('check');

        } else {

            checkboxes.iCheck('uncheck');

        }

    });



    checkboxes.on('ifChanged', function(event){

        if(checkboxes.filter(':checked').length == checkboxes.length) {

            checkAll.prop('checked', 'checked');

        } else {

            checkAll.removeProp('checked');

        }

        checkAll.iCheck('update');

    });



  }); /*end doc ready*/

</script>